name: Sonatype Nexus Deployment

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          cache: maven
          server-id: sonatype-nexus
          server-username: ${{ secrets.SONATYPE_USER }}
          server-password: ${{ secrets.SONATYPE_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: ${{ secrets.GPG_PASSWORD }}
      - name: Publish to Sonatype Nexus
        run: mvn clean deploy -Poss-release -B -DskipTests -Dgpg.passphrase=${{ secrets.GPG_PASSWORD }}